// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import("ant-design-vue/es")["LayoutContent"];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    Content: typeof import('./src/components/Layout/content/index.vue')['default']
    Header: typeof import('./src/components/Layout/header/index.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LayoutSider: typeof import("./src/components/Layout/sider/LayoutSider.vue")["default"];
    Menu: typeof import('./src/components/Layout/menu/index.vue')['default']
    MenuContent: typeof import('./src/components/Layout/menu/MenuContent.vue')['default']
    MenuLogo: typeof import('./src/components/Layout/menu/MenuLogo.vue')['default']
    Page: typeof import('./src/components/Layout/page/index.vue')['default']
    Provider: typeof import('./src/components/Layout/provider/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import("./src/components/Layout/sider/index.vue")["default"];
  }
}

export {}
